/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.challengercity.revise;

/**
 *
 * @author Ben
 */
public class ColorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ColorPanel
     */
    public ColorPanel() {
        initComponents();
    }
    
    public ColorPanel(ReviseMain frame) {
        initComponents();
        myFrame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button0 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttona = new javax.swing.JButton();
        buttonb = new javax.swing.JButton();
        buttonc = new javax.swing.JButton();
        buttond = new javax.swing.JButton();
        buttone = new javax.swing.JButton();
        buttonf = new javax.swing.JButton();

        setBackground(new java.awt.Color(191, 182, 152));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 21, 21), 5));
        setToolTipText("Colors");

        button0.setBackground(new java.awt.Color(0, 0, 0));
        button0.setToolTipText("0");
        button0.setMaximumSize(new java.awt.Dimension(0, 0));
        button0.setMinimumSize(new java.awt.Dimension(0, 0));
        button0.setPreferredSize(new java.awt.Dimension(15, 15));
        button0.setSize(new java.awt.Dimension(15, 15));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 0, 170));
        button1.setToolTipText("1");
        button1.setMaximumSize(new java.awt.Dimension(0, 0));
        button1.setMinimumSize(new java.awt.Dimension(0, 0));
        button1.setPreferredSize(new java.awt.Dimension(15, 15));
        button1.setSize(new java.awt.Dimension(15, 15));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 170, 0));
        button2.setToolTipText("2");
        button2.setMaximumSize(new java.awt.Dimension(0, 0));
        button2.setMinimumSize(new java.awt.Dimension(0, 0));
        button2.setPreferredSize(new java.awt.Dimension(15, 15));
        button2.setSize(new java.awt.Dimension(15, 15));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(0, 170, 170));
        button3.setToolTipText("3");
        button3.setMaximumSize(new java.awt.Dimension(0, 0));
        button3.setMinimumSize(new java.awt.Dimension(0, 0));
        button3.setPreferredSize(new java.awt.Dimension(15, 15));
        button3.setSize(new java.awt.Dimension(15, 15));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(170, 0, 0));
        button4.setToolTipText("4");
        button4.setMaximumSize(new java.awt.Dimension(0, 0));
        button4.setMinimumSize(new java.awt.Dimension(0, 0));
        button4.setPreferredSize(new java.awt.Dimension(15, 15));
        button4.setSize(new java.awt.Dimension(15, 15));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(170, 0, 170));
        button5.setToolTipText("5");
        button5.setMaximumSize(new java.awt.Dimension(0, 0));
        button5.setMinimumSize(new java.awt.Dimension(0, 0));
        button5.setPreferredSize(new java.awt.Dimension(15, 15));
        button5.setSize(new java.awt.Dimension(15, 15));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(170, 170, 0));
        button6.setToolTipText("6");
        button6.setMaximumSize(new java.awt.Dimension(0, 0));
        button6.setMinimumSize(new java.awt.Dimension(0, 0));
        button6.setPreferredSize(new java.awt.Dimension(15, 15));
        button6.setSize(new java.awt.Dimension(15, 15));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(170, 170, 170));
        button7.setToolTipText("7");
        button7.setMaximumSize(new java.awt.Dimension(0, 0));
        button7.setMinimumSize(new java.awt.Dimension(0, 0));
        button7.setPreferredSize(new java.awt.Dimension(15, 15));
        button7.setSize(new java.awt.Dimension(15, 15));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(85, 85, 85));
        button8.setToolTipText("8");
        button8.setMaximumSize(new java.awt.Dimension(0, 0));
        button8.setMinimumSize(new java.awt.Dimension(0, 0));
        button8.setPreferredSize(new java.awt.Dimension(15, 15));
        button8.setSize(new java.awt.Dimension(15, 15));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(85, 85, 255));
        button9.setToolTipText("9");
        button9.setMaximumSize(new java.awt.Dimension(0, 0));
        button9.setMinimumSize(new java.awt.Dimension(0, 0));
        button9.setPreferredSize(new java.awt.Dimension(15, 15));
        button9.setSize(new java.awt.Dimension(15, 15));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttona.setBackground(new java.awt.Color(85, 255, 85));
        buttona.setToolTipText("a");
        buttona.setMaximumSize(new java.awt.Dimension(0, 0));
        buttona.setMinimumSize(new java.awt.Dimension(0, 0));
        buttona.setPreferredSize(new java.awt.Dimension(15, 15));
        buttona.setSize(new java.awt.Dimension(15, 15));
        buttona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaActionPerformed(evt);
            }
        });

        buttonb.setBackground(new java.awt.Color(85, 255, 255));
        buttonb.setToolTipText("b");
        buttonb.setMaximumSize(new java.awt.Dimension(0, 0));
        buttonb.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonb.setPreferredSize(new java.awt.Dimension(15, 15));
        buttonb.setSize(new java.awt.Dimension(15, 15));
        buttonb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbActionPerformed(evt);
            }
        });

        buttonc.setBackground(new java.awt.Color(255, 85, 85));
        buttonc.setToolTipText("c");
        buttonc.setMaximumSize(new java.awt.Dimension(0, 0));
        buttonc.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonc.setPreferredSize(new java.awt.Dimension(15, 15));
        buttonc.setSize(new java.awt.Dimension(15, 15));
        buttonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncActionPerformed(evt);
            }
        });

        buttond.setBackground(new java.awt.Color(255, 85, 255));
        buttond.setToolTipText("d");
        buttond.setMaximumSize(new java.awt.Dimension(0, 0));
        buttond.setMinimumSize(new java.awt.Dimension(0, 0));
        buttond.setPreferredSize(new java.awt.Dimension(15, 15));
        buttond.setSize(new java.awt.Dimension(15, 15));
        buttond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondActionPerformed(evt);
            }
        });

        buttone.setBackground(new java.awt.Color(255, 255, 85));
        buttone.setToolTipText("e");
        buttone.setMaximumSize(new java.awt.Dimension(0, 0));
        buttone.setMinimumSize(new java.awt.Dimension(0, 0));
        buttone.setPreferredSize(new java.awt.Dimension(15, 15));
        buttone.setSize(new java.awt.Dimension(15, 15));
        buttone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoneActionPerformed(evt);
            }
        });

        buttonf.setBackground(new java.awt.Color(255, 255, 255));
        buttonf.setToolTipText("f");
        buttonf.setMaximumSize(new java.awt.Dimension(0, 0));
        buttonf.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonf.setPreferredSize(new java.awt.Dimension(15, 15));
        buttonf.setSize(new java.awt.Dimension(15, 15));
        buttonf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonfActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(button4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(button0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(button8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(button9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttona, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(buttonc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttond, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttona, buttonb, buttonc, buttond, buttone, buttonf}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(button3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(button5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(button8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttona, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buttonc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttond, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttona, buttonb, buttonc, buttond, buttone, buttonf}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
   
    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        myFrame.addColor("0");
    }//GEN-LAST:event_button0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        myFrame.addColor("1");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        myFrame.addColor("2");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        myFrame.addColor("3");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        myFrame.addColor("4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        myFrame.addColor("5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        myFrame.addColor("6");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        myFrame.addColor("7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        myFrame.addColor("8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        myFrame.addColor("9");
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaActionPerformed
        myFrame.addColor("a");
    }//GEN-LAST:event_buttonaActionPerformed

    private void buttonbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbActionPerformed
        myFrame.addColor("b");
    }//GEN-LAST:event_buttonbActionPerformed

    private void buttoncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncActionPerformed
        myFrame.addColor("c");
    }//GEN-LAST:event_buttoncActionPerformed

    private void buttondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondActionPerformed
        myFrame.addColor("d");
    }//GEN-LAST:event_buttondActionPerformed

    private void buttoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoneActionPerformed
        myFrame.addColor("e");
    }//GEN-LAST:event_buttoneActionPerformed

    private void buttonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonfActionPerformed
        myFrame.addColor("f");
    }//GEN-LAST:event_buttonfActionPerformed

    public ReviseMain myFrame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttona;
    private javax.swing.JButton buttonb;
    private javax.swing.JButton buttonc;
    private javax.swing.JButton buttond;
    private javax.swing.JButton buttone;
    private javax.swing.JButton buttonf;
    // End of variables declaration//GEN-END:variables
}
