/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.challengercity.revise;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.File;
import net.minecraft.src.*;
/**
 *
 * @author Ben
 */
public class InvGUI extends javax.swing.JFrame {

    /**
     * Creates new form InvGUI
     */
    public InvGUI(ReviseMain frame, boolean exportssp, net.minecraft.src.NBTTagCompound loadedTag, File file) {
        initComponents();
        this.myFrame = frame;
        this.loadedTag = loadedTag;
        this.openFile = file;
        this.exportssp = exportssp;
        setUpIcons();
        loadInventory();
        updateSlotButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Revise Inventory");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(298, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(4, 102, 32, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton2.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton2.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(36, 102, 32, 32);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton3.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton3.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(68, 102, 32, 32);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton4.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton4.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 102, 32, 32);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton5.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton5.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(132, 102, 32, 32);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton6.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton6.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(164, 102, 32, 32);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton7.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton7.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(196, 102, 32, 32);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton8.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton8.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(228, 102, 32, 32);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton9.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton9.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(260, 102, 32, 32);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton10.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton10.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(4, 4, 32, 32);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton11.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton11.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton11.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(36, 4, 32, 32);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton12.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton12.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton12.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(68, 4, 32, 32);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton13.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton13.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(100, 4, 32, 32);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton14.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton14.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(132, 4, 32, 32);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton15.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton15.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(164, 4, 32, 32);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton16.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton16.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(196, 4, 32, 32);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton17.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton17.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton17.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(228, 4, 32, 32);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton18.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton18.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton18.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(260, 4, 32, 32);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton19.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton19.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton19.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(4, 36, 32, 32);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton20.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton20.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton20.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(36, 36, 32, 32);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton21.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton21.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton21.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(68, 36, 32, 32);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton22.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton22.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton22.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(100, 36, 32, 32);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton23.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton23.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton23.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(132, 36, 32, 32);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton24.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton24.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton24.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(164, 36, 32, 32);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton25.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton25.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton25.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(196, 36, 32, 32);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton26.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton26.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton26.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(228, 36, 32, 32);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton27.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton27.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton27.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(260, 36, 32, 32);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton28.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton28.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton28.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(4, 68, 32, 32);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton29.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton29.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton29.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(36, 68, 32, 32);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton30.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton30.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton30.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(68, 68, 32, 32);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton31.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton31.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton31.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(100, 68, 32, 32);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton32.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton32.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton32.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(132, 68, 32, 32);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton33.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton33.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton33.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(164, 68, 32, 32);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton34.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton34.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton34.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(196, 68, 32, 32);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton35.setBorder(null);
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton35.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton35.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton35.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(228, 68, 32, 32);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"))); // NOI18N
        jButton36.setBorder(null);
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton36.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton36.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton36.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(260, 68, 32, 32);

        exportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/ExportButton.png"))); // NOI18N
        exportButton.setBorder(null);
        exportButton.setBorderPainted(false);
        exportButton.setContentAreaFilled(false);
        exportButton.setRolloverEnabled(true);
        exportButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/ExportButtonS.png"))); // NOI18N
        exportButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/ExportButtonS.png"))); // NOI18N
        exportButton.setSelected(true);
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exportButton);
        exportButton.setBounds(225, 200, 70, 20);

        titleLabel.setFont(com.challengercity.revise.ReviseMain.mcFont12);
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Title: ");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(10, 140, 280, 20);

        authorLabel.setFont(com.challengercity.revise.ReviseMain.mcFont12);
        authorLabel.setText("Author: ");
        getContentPane().add(authorLabel);
        authorLabel.setBounds(10, 160, 280, 20);

        instructions.setFont(com.challengercity.revise.ReviseMain.mcFont12);
        instructions.setText("Select an empty slot.");
        getContentPane().add(instructions);
        instructions.setBounds(10, 210, 210, 16);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/BackgroundGrid.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 296, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="SlotButton ActionPerformed">
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectSlot((byte) 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectSlot((byte) 2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectSlot((byte) 3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        selectSlot((byte) 4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        selectSlot((byte) 5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        selectSlot((byte) 6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        selectSlot((byte) 7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        selectSlot((byte) 8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        selectSlot((byte) 9);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        selectSlot((byte) 10);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        selectSlot((byte) 11);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        selectSlot((byte) 12);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        selectSlot((byte) 13);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        selectSlot((byte) 14);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        selectSlot((byte) 15);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        selectSlot((byte) 16);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        selectSlot((byte) 17);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        selectSlot((byte) 18);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        selectSlot((byte) 19);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        selectSlot((byte) 20);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        selectSlot((byte) 21);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        selectSlot((byte) 22);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        selectSlot((byte) 23);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        selectSlot((byte) 24);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        selectSlot((byte) 25);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        selectSlot((byte) 26);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        selectSlot((byte) 27);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        selectSlot((byte) 28);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        selectSlot((byte) 29);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        selectSlot((byte) 30);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        selectSlot((byte) 31);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        selectSlot((byte) 32);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        selectSlot((byte) 33);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        selectSlot((byte) 34);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        selectSlot((byte) 35);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        selectSlot((byte) 36);
    }//GEN-LAST:event_jButton36ActionPerformed
    // </editor-fold>
    
    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        NBTTagCompound itemTag = new NBTTagCompound();
        NBTTagCompound innerBookTag = new NBTTagCompound();
        NBTTagList newInv = new NBTTagList(); // Create new inventory tag
        
        /**/
        for (int i = 0; i < invTag.tagCount(); i++) { // Look for books
            NBTTagCompound itemTag2 = (NBTTagCompound) invTag.tagAt(i); // Get the item in the current slot
            newInv.appendTag(itemTag2); // Add the item, may be changed, to the new inventory
        } // End inventory scan
        /**/
        
        itemTag.setByte("Slot", selectedSlot);
        itemTag.setByte("Count", (byte) 1);
        itemTag.setShort("Damage", (short) 0);
        if (myFrame.ingameToggle.isSelected()) {
            itemTag.setShort("id", (short) 386);
        } else {
            itemTag.setShort("id", (short) 387);
        }
        innerBookTag.setString("title", myFrame.title);
        innerBookTag.setString("author", myFrame.author);
        NBTTagList newPages = new NBTTagList(); // Create a new Pages List
        for (int j = 0; j < myFrame.pages.size(); j++) { // For all the pages
            if (myFrame.pages.get(j) != null && !myFrame.pages.get(j).equals("")) { // If they are not empty
                newPages.appendTag(new NBTTagString("" + j, myFrame.pages.get(j))); // Set them to what's loaded in the editor
            }
        }
        if(myFrame.pages.size() == 0) {
            newPages.appendTag(new NBTTagString("0", " "));
        }
        innerBookTag.setTag("pages", newPages); // Overwrite the old pages with the new pages
        
        itemTag.setCompoundTag("tag", innerBookTag);
        newInv.appendTag(itemTag);
        if (!exportssp) {
            loadedTag.setTag("Inventory", newInv);
        } else {
            NBTTagCompound dataTag = loadedTag.getCompoundTag("Data"); // Open Level Tag
            NBTTagCompound playerTag = dataTag.getCompoundTag("Player");
            
            playerTag.setTag("Inventory", newInv); // Save Changed Level Tag
            dataTag.setCompoundTag("Player", playerTag);
            loadedTag.setCompoundTag("Data", dataTag);
        }
        
        // Save the edited dataTag
        try {
            System.out.println("File: " + openFile); // Print file address
            FileOutputStream fileoutputstream = new FileOutputStream(openFile);
            CompressedStreamTools.writeCompressed(loadedTag, fileoutputstream);
            fileoutputstream.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        this.dispose();
    }//GEN-LAST:event_exportButtonActionPerformed
    
    private void selectSlot(byte buttonID) {
        System.out.println("Selected Slot "+(buttonID-1));
        selectedSlot = (byte)(buttonID-1);
        boolean doesItemTagExist = false;
        for (int i = 0; i < invTag.tagCount(); i++) { // Scan inventory for correct book
            NBTTagCompound itemTag = (NBTTagCompound) invTag.tagAt(i); // Get the item at this index
            if (itemTag.getByte("Slot") == buttonID-1) {
                doesItemTagExist = true;
                switch (itemTag.getShort("id")) {
                    case 386:
                        updateBookInfo("Untitled", "Anonymous");
                        break;
                    case 387:
                        updateBookInfo(itemTag.getCompoundTag("tag").getString("title"),itemTag.getCompoundTag("tag").getString("author"));
                        break;
                    default:
                        updateBookInfo("Not a Book","");
                        break;
                }
            }
            if (!doesItemTagExist) {
                updateBookInfo("Empty Slot","");
            }
        }
    }
    
    private void loadInventory() {
        if (!exportssp) {
            invTag = loadedTag.getTagList("Inventory");
        } else {
            NBTTagCompound dataTag = loadedTag.getCompoundTag("Data");
            NBTTagCompound playerTag = dataTag.getCompoundTag("Player");
            invTag = playerTag.getTagList("Inventory");
        }
    }
    
    private void updateSlotButtons() {
        for (int i = 0; i < invTag.tagCount(); i++) { // Scan Inventory
            NBTTagCompound itemTag = (NBTTagCompound) invTag.tagAt(i); // Get the item at this index
            switch (itemTag.getShort("id")) {
                case 386:
                    getSlotButtonFromID(itemTag.getByte("Slot")).setIcon(iconUnsigned);
                    break;
                case 387:
                    getSlotButtonFromID(itemTag.getByte("Slot")).setIcon(iconSigned);
                    break;
                default:
                    getSlotButtonFromID(itemTag.getByte("Slot")).setIcon(iconOther);
                    getSlotButtonFromID(itemTag.getByte("Slot")).setEnabled(false);
                    break;
            }
        }
    }
    
    private javax.swing.JButton getSlotButtonFromID(byte id) {
        switch (id+1) {
            case 1:
                return jButton1;
            case 2:
                return jButton2;
            case 3:
                return jButton3;
            case 4:
                return jButton4;
            case 5:
                return jButton5;
            case 6:
                return jButton6;
            case 7:
                return jButton7;
            case 8:
                return jButton8;
            case 9:
                return jButton9;
            case 10:
                return jButton10;
            case 11:
                return jButton11;
            case 12:
                return jButton12;
            case 13:
                return jButton13;
            case 14:
                return jButton14;
            case 15:
                return jButton15;
            case 16:
                return jButton16;
            case 17:
                return jButton17;
            case 18:
                return jButton18;
            case 19:
                return jButton19;
            case 20:
                return jButton20;
            case 21:
                return jButton21;
            case 22:
                return jButton22;
            case 23:
                return jButton23;
            case 24:
                return jButton24;
            case 25:
                return jButton25;
            case 26:
                return jButton26;
            case 27:
                return jButton27;
            case 28:
                return jButton28;
            case 29:
                return jButton29;
            case 30:
                return jButton30;
            case 31:
                return jButton31;
            case 32:
                return jButton32;
            case 33:
                return jButton33;
            case 34:
                return jButton34;
            case 35:
                return jButton35;
            case 36:
                return jButton36;
        }
        return jButton1;
    }
    
    private void updateBookInfo(String title, String author) {
        titleLabel.setText("Title: "+title);
        authorLabel.setText("Author: "+author);
    }
    
    public void setUpIcons() {
        try {
            iconEmpty = new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Empty.png"));

            iconOther = new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Other.png"));
            
            iconSigned = new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Signed.png"));

            iconUnsigned = new javax.swing.ImageIcon(getClass().getResource("/com/challengercity/revise/resources/InvGUI/Unsigned.png"));
            
        } catch (Exception ex) {ex.printStackTrace();}
    }
    
    private javax.swing.ImageIcon iconEmpty;
    private javax.swing.ImageIcon iconOther;
    private javax.swing.ImageIcon iconSigned;
    private javax.swing.ImageIcon iconUnsigned;
    
    private File openFile;
    private net.minecraft.src.NBTTagList invTag;
    private net.minecraft.src.NBTTagCompound loadedTag;
    private boolean exportssp;
    private byte selectedSlot;
    private ReviseMain myFrame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel instructions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
